package com.company.oop.furniture.commands;

public enum CommandType {
    CREATECOMPANY,
    ADDFURNITURETOCOMPANY,
    REMOVEFURNITUREFROMCOMPANY,
    FINDFURNITUREFROMCOMPANY,
    SHOWCOMPANYCATALOG,
    CREATECHAIR,
    CREATETABLE,
    SETCHAIRHEIGHT,
    CONVERTCHAIR
}
